CREATE TABLE IF NOT EXISTS air_quality (
    _time TIMESTAMP NOT NULL,
    pm10 DOUBLE PRECISION NOT NULL,
    pm2_5 DOUBLE PRECISION NOT NULL,
    carbon_monoxide DOUBLE PRECISION NOT NULL,
    carbon_dioxide DOUBLE PRECISION NULL,
    nitrogen_dioxide DOUBLE PRECISION NOT NULL,
    sulphur_dioxide DOUBLE PRECISION NOT NULL,
    ozone DOUBLE PRECISION NOT NULL,
    methane DOUBLE PRECISION NULL,
    uv_index DOUBLE PRECISION NOT NULL,
    dust DOUBLE PRECISION NOT NULL,
    aerosol_optical_depth DOUBLE PRECISION NOT NULL,
    us_aqi BIGINT NOT NULL,
    insert_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)